# theme: jekyll-theme-minimal
title: Ehsan's homepage
description: Bookmark this to keep an eye on my project updates!
email: ghafari.5000@gmail.com
timezone: UTC
baseurl: "/"
permalink: "/:title/"
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
author: Ehsan Ghaffar
